(function($){"use strict";$('.header-menu a[href="#"]').on('click',function(event){event.preventDefault();});$(".header-menu").menumaker({title:'<i class="fa fa-bars"></i>',format:"multitoggle"});var mainHeader=$('.main-header');if($(window).scrollTop()>100)$('.main-header').addClass('sticky fadeInDown')
$(window).on('scroll',function(e){if($(this).scrollTop()<100){$('.main-header').removeClass('sticky fadeInDown')}else
$('.main-header').addClass('sticky fadeInDown')});var bgImg=$('[data-bg-img]');bgImg.css('background',function(){return 'url('+$(this).data('bg-img')+') center center';});$('.parsley-validate, .parsley-validate form').parsley();var $backToTopBtn=$('.back-to-top');if($backToTopBtn.length){var scrollTrigger=400,backToTop=function(){var scrollTop=$(window).scrollTop();if(scrollTop>scrollTrigger){$backToTopBtn.addClass('show');}else{$backToTopBtn.removeClass('show');}};backToTop();$(window).on('scroll',function(){backToTop();});$backToTopBtn.on('click',function(e){e.preventDefault();$('html,body').animate({scrollTop:0},700);});}
$('.feature-carousel').owlCarousel({loop:true,margin:30,center:true,dots:true,autoplay:true,autoplayTimeout:4000,responsive:{0:{items:1,},575:{items:1,},768:{items:2},991:{items:2},992:{items:3}}})
$('.app-carousel').owlCarousel({loop:true,margin:30,center:true,dots:true,responsive:{0:{items:1},575:{items:1},700:{items:1},1000:{items:1}}})
jQuery('img.svg').each(function(){var $img=jQuery(this);var imgID=$img.attr('id');var imgClass=$img.attr('class');var imgURL=$img.attr('src');jQuery.get(imgURL,function(data){var $svg=jQuery(data).find('svg');if(typeof imgID!=='undefined'){$svg=$svg.attr('id',imgID);}
if(typeof imgClass!=='undefined'){$svg=$svg.attr('class',imgClass+' replaced-svg');}
$svg=$svg.removeAttr('xmlns:a');if(!$svg.attr('viewBox')&&$svg.attr('height')&&$svg.attr('width')){$svg.attr('viewBox','0 0 '+$svg.attr('height')+' '+$svg.attr('width'));}
$img.replaceWith($svg);},'xml');});$('.contact-form').on('submit','form',function(e){e.preventDefault();var $el=$(this);$.post($el.attr('action'),$el.serialize(),function(res){res=$.parseJSON(res);$el.parent('.contact-page-form').find('.form-response').html('<span>'+res[1]+'</span>');});});$(window).on('load',function(){function removePreloader(){var preLoader=$('.preLoader');preLoader.fadeOut();}
setTimeout(removePreloader,250);});$(window).on('load',function(){var $animateEl=$('[data-animate]');$animateEl.each(function(){var $el=$(this),$name=$el.data('animate'),$duration=$el.data('duration'),$delay=$el.data('delay');$duration=typeof $duration==='undefined'?'0.6':$duration;$delay=typeof $delay==='undefined'?'.1':$delay;$el.waypoint(function(){$el.addClass('animated '+$name).css({'animation-duration':$duration+'s','animation-delay':$delay+'s'});},{offset:'93%'});});});$('.counter').counterUp({});var $parallaxLayers=$('[data-trigger="parallax_layers"]');if($parallaxLayers.length){$parallaxLayers.each(function(){new Parallax($(this)[0],{selector:'[data-depth]'});});}
var t=$(".video-btn");t.length&&t.magnificPopup({type:"iframe"})
$('.single-price-plan').on('mouseenter',function(){$(this).addClass('active').parent().siblings().find('.single-price-plan').removeClass('active');})
$('.partner-carousel').owlCarousel({loop:true,margin:20,nav:false,dots:false,autoplay:true,autoplayTimeout:4000,autoplaySpeed:3000,responsive:{0:{items:1},500:{items:3},768:{items:4},992:{items:5}}})
$(".header-menu ul li a").on("click",function(t){var c=$(this.hash);if(c.length!==0){$("html,body").animate({scrollTop:c.offset().top},700);}})
let author=$('.author-carousel')
author.owlCarousel({loop:true,margin:20,nav:true,center:true,dots:false,responsive:{0:{items:1},500:{items:1},768:{items:1},992:{items:1}}})
let author_cumment=$('.author-comment-carousel');author_cumment.owlCarousel({loop:true,margin:20,nav:true,navText:['<i class="fa fa-angle-right">','<i class="fa fa-angle-right">'],dots:false,responsive:{0:{items:1},500:{items:1},768:{items:1},992:{items:1}}});$('.author-comment-carousel .owl-next').on('click',function(){$('.author-carousel .owl-next').click()});$('.author-comment-carousel .owl-prev').on('click',function(){$('.author-carousel .owl-prev').click()});$(window).on('resize',()=>{if($(window).width()>=975){$('.main-header.header-2 .logo .main-logo2').attr('src','/aero-indir/aero_dosyalar/gorseller/aerologo2.png')}else if($(window).width()<=975){$('.main-header.header-2 .logo .main-logo2').attr('src','/aero-indir/aero_dosyalar/gorseller/aerologo.png')}})
if($(window).width()>=975){$('.main-header.header-2 .logo .main-logo2').attr('src','/aero-indir/aero_dosyalar/gorseller/aerologo2.png')}else if($(window).width()<=975){$('.main-header.header-2 .logo .main-logo2').attr('src','/aero-indir/aero_dosyalar/gorseller/aerologo.png')}})(jQuery);